contact_links:
  - name: OOEP Support
    url: https://ooep.freshdesk.com/support/home
    about: If you need help with how to use Coauthor (as opposed to reporting bugs or feature requests), feel free to ask questions here.
